name: Main CI

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: ci-main
  cancel-in-progress: true

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11
          run_install: false
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run linter
        run: pnpm run lint
